MBASE IMPORT-ASS* ((TRANSITIVITY SATZ-1.5 TRICHO-NOT= INVERSE-MULT
                    MONOTONY NEUTRAL-MULT SATZ-1.10A))
RULES FORALLI default default default
RULES IMPI default
OMEGA-BASIC LEMMA (L3) ((< NULL A1))
OMEGA-BASIC LEMMA (L3) ((NOT (= A1 NULL)))
OMEGA-BASIC LEMMA (L3) ((NOT (= NULL A1)))
OMEGA-BASIC LEMMA (L3) ((= (* EINS (INV A1)) (INV A1)))
OMEGA-BASIC LEMMA (L3) ((= (* A1 (INV A1)) EINS))
TACTICS ASSERTION ((L2 SATZ-1.5)) (TRANSITIVITY) (L4)
TACTICS ASSERTION ((L4)) (TRICHO-NOT=) (L5)
TACTICS ASSERTION ((L4)) (TRICHO-NOT=) (L6)
TACTICS ASSERTION (NIL) (NEUTRAL-MULT) (L7)
TACTICS ASSERTION ((L5)) (INVERSE-MULT) (L8)
RULES ANDI default default default
TACTICS ASSERTION ((L5 L4)) (SATZ-1.10A) (L9)
TACTICS =SUBST default (NIL) (L8) ((2))
TACTICS =SUBST default (NIL) (L7) ((1))
TACTICS ASSERTION ((L9 L2)) (MONOTONY) (L12)
