DECLARATION DECLARE ((CONSTANTS (M NUM) (N NUM) (K NUM)))
RULES NOTI default default
MBASE IMPORT-ASS (RAT-CRITERION)
TACTICS FORALLE-SORT default default ((SQRT 2)) default
TACTICS EXISTSE-SORT default default (N) default
TACTICS ANDE default default default
TACTICS EXISTSE-SORT (L7) default (M) default
TACTICS ANDE* (L8) (NIL)
TACTICS ISLAND-TACTIC nil ((l11)) ((= (TIMES 2 (POWER N 2)) (POWER M 2)))
TACTICS ISLAND-TACTIC nil ((l13)) ((EVENP (POWER M 2)))
TACTICS ISLAND-TACTIC nil ((l14 l10)) ((EVENP M))
RULES DEFN-EXPAND (l15) default default
TACTICS EXISTSE-SORT (L16) default (K) default
TACTICS ANDE (l17) default default
TACTICS ISLAND-TACTIC nil ((l20 l13)) ((= (POWER N 2) (TIMES 2 (POWER K 2))))
TACTICS ISLAND-TACTIC nil ((l21)) ((EVENP (POWER N 2)))
TACTICS ISLAND-TACTIC nil ((l22 l6)) ((EVENP N))
TACTICS ISLAND-TACTIC nil ((l15 l23 l6 l10)) ((COMMON-DIVISOR N M 2))
TACTICS ISLAND-TACTIC (l18) ((l12 l24)) (FALSE)
