DECLARATION DECLARE ((CONSTANTS (M NUM) (N NUM) (K NUM)))
RULES NOTI default default
MBASE IMPORT-ASS (RAT-CRITERION)
TACTICS FORALLE-SORT default default ((SQRT 2)) default
TACTICS MEXISTSE-SORT* default default default ((n m))
TACTICS ANDE (L9) default default
TACTICS ISLAND-TACTIC nil ((l11 l6 l8)) ((= (TIMES 2 (POWER N 2)) (POWER M 2)))
TACTICS ISLAND-TACTIC nil ((l13 l6 l8)) ((EVENP (POWER M 2)))
TACTICS ISLAND-TACTIC nil ((l14 l8)) ((EVENP M))
RULES DEFN-EXPAND (l15) default default
TACTICS MEXISTSE-SORT* default (l16) default ((k))
TACTICS ISLAND-TACTIC nil ((l19 l13 l6 l8 l18)) ((= (POWER N 2) (TIMES 2 (POWER K 2))))
TACTICS ISLAND-TACTIC nil ((l21 l6 l18)) ((EVENP (POWER N 2)))
TACTICS ISLAND-TACTIC nil ((l22 l6)) ((EVENP N))
TACTICS ISLAND-TACTIC nil ((l15 l23 l6 l8)) ((COMMON-DIVISOR N M 2))
TACTICS ISLAND-TACTIC (l20) ((l12 l24)) (FALSE)
