EXTERN CALL-CAS (POL-ADD1) ((1)) (MYCAS)
RULES DEFN-CONTRACT (L1) (=) ((0))
RULES FORALLI default default (NIL)
RULES IMPI (L3)
RULES WEAKEN (L5) (L4)
VERIFY CHECK-PROOF ((ARITH-SIMPLIFY EXPAND-NUM))

